version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
    ports: ['5000:5000']
    volumes: ['./src:/app']
