version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:

    docker:
      - image: circleci/python:3.6
        
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gardener_testing
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ./run_migrations
          name: Migration
      - run:
          command: ./run_linter
          nama: Linter

      - run:
          command: ./run_test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test

